services:  
  mongo:
    image: mongo:6.0
    container_name: mongo-server
    command:
      - --storageEngine=wiredTiger
    networks:
      - appnet
    volumes:
      - C:/Deploys/mongo/comisiones:/data/db
    ports:
      - "27019:27017"
networks:
  appnet:
    driver: bridge
volumes:
  generated:
    driver: local