services:
  app:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3010:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo/gastospassa
    depends_on:
      - mongo
    networks:
      - appnet
  mongo:
    image: mongo:6.0
    command:
      - --storageEngine=wiredTiger
    networks:
      - appnet
    volumes:
      - ./data/gastospassa:/data/db
    ports:
      - "27018:27017"
networks:
  appnet:
    driver: bridge
volumes:
  generated:
    driver: local