services:
  app:
    container_name: portalcomisiones
    image: eljeque/portalcomisiones:latest
    ports:
      - '3011:3000'
    environment:
      ROOT_URL: ${APP_ROOT_URL:-http://localhost}
      MONGO_URL: mongodb://mongo-server/comisiones
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  generated:
    driver: local