module.exports = {
  windows_api: "http://26.168.101.211:49824/api/querys/ejecutar",
  windows_api_post: "http://26.168.101.211:49824/api/querys/ejecutarPost",
  body_fabrica: {
    usuario: "abacoapp",
    contrasena: "S1stem@Pas5@",
    servidor: "26.189.208.155\\SERVERR2",
    baseDatos: "FABRICA_PASSA",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
  body_empresas: {
    usuario: "abacoapp",
    contrasena: "S1stem@Pas5@",
    servidor: "26.189.208.155\\SERVERR2",
    baseDatos: "EMPRESAS",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
  body_bdseleccionada: {
    servidor: "26.189.208.155\\SERVERR2",
    baseDatos: "",
    usuario: "abacoapp",
    contrasena: "S1stem@Pas5@",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
};
