module.exports = {
  windows_api: "http://192.168.100.106/querysv2/api/querys/ejecutar",
  body_fabrica: {
    usuario: "sa",
    contrasena: "SU2orange!",
    servidor: "192.168.100.106",
    baseDatos: "FABRICA_PASSA",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
  body_empresas: {
    usuario: "sa",
    contrasena: "SU2orange!",
    servidor: "192.168.100.106",
    baseDatos: "EMPRESAS",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
  body_bdseleccionada: {
    usuario: "sa",
    contrasena: "SU2orange!",
    servidor: "192.168.100.106",
    baseDatos: "",
    parametros: [],
    esValido: true,
    mensaje: "",
    resultado: "",
  },
};
